name: CI/CD Pipeline - Python Docker

on:
  push:
    branches:
      - main

jobs:
  # === Étape 1 : Tests Python ===
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (allow empty)
        run: pytest || echo "No tests found"   # ou python -m unittest si tu utilises unittest

  # === Étape 2 : Build & Push Docker Image ===
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-word-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/hello-word-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/hello-word-app:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-word-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-word-app:latest

  # === Étape 3 : Déploiement sur Azure Web App ===
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'my-azure-webapp'
          images: '${{ secrets.DOCKER_USERNAME }}/hello-word-app:latest'
